name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  install:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_NAME: ${{ steps.generate-uuid.outputs.IMAGE_NAME }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate UUID
        id: generate-uuid
        run: |
          UUID=$(sha256sum package{,-lock}.json | sha256sum | awk '{ print $1 }')
          echo "IMAGE_NAME=${UUID}" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=${UUID}" >> $GITHUB_ENV
      - name: Check if image exists
        id: check-image-exists
        run: |
          if ! docker pull ttl.sh/${IMAGE_NAME}:1h; then
            echo "BUILD_IMAGE=true" >> $GITHUB_OUTPUT
          fi
      - name: Build docker image
        if: steps.check-image-exists.outputs.BUILD_IMAGE == 'true'
        run: docker build -t ttl.sh/${IMAGE_NAME}:1h .
      - name: Push docker image
        if: steps.check-image-exists.outputs.BUILD_IMAGE == 'true'
        run: docker push ttl.sh/${IMAGE_NAME}:1h

  lint:
    runs-on: ubuntu-latest
    needs: install
    container:
      image: ttl.sh/${{ needs.install.outputs.IMAGE_NAME }}:1h
    steps:
      - uses: actions/checkout@v4
      - run: cd /app && npm run lint

  test:
    runs-on: ubuntu-latest
    needs: install
    container:
      image: ttl.sh/${{ needs.install.outputs.IMAGE_NAME }}:1h
    steps:
      - uses: actions/checkout@v4
      - run: cd /app && npm test
