# .github/workflows/ci.yml
name: CI
on:
  push: # Déclenchement à chaque push/merge
    branches:
      - master # sur la branche `master' uniquement

jobs:
  deploy: # Nom du premier job
    runs-on: ubuntu-latest # macos, windows…
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc" # Contient "v22.19.0"

      - name: Install dependencies
        run: npm ci

      - name: Test project
        run: npm test

      - name: Lint project
        run: npm run lint

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Prepare Allure results
        run: mkdir -p allure-results

      - name: Build test report
        uses: andgineer/allure-report@v3
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history