# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - master # déclenche seulement sur la branche master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v5

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Run tests
      - name: Test project
        run: npm test

      # 5. Lint project
      - name: Lint project
        run: npm run lint

      # 6. Charger l’historique des rapports depuis gh-pages
      - name: Checkout gh-pages (history)
        uses: actions/checkout@v5
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-dir

      # 7. Générer le rapport Allure
      - name: Generate Allure report
        uses: andgineer/allure-report@v3
        if: always()
        with:
          allure-results: build/allure-results
          website: gh-pages-dir
          reports-site-path: allure-report

      # 8. Publier sur GitHub Pages
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: gh-pages-dir
