# .github/workflows/ci.yml
name: CI # Nom du workflow
on:
  push: # Déclenchement à chaque push/merge
    branches:
      - master # sur la branche 'master' uniquement
jobs:
  deploy:  # Nom du 1er job
    runs-on: windows-latest
    step:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with : 
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm build project
      - name: Deploy project
        run: npm run deploy
      - name: Test
        npm test
      - name: Lint
        run: npm run lint
    jobs:
      test:
        needs: build

