name: CI
on: 
  push: 
    branches: master
  pull_request:
    branches: master

jobs: 
  init:
    runs-on: 
      - ubuntu-latest
      - windows-latest
      - macos-latest

    steps: 
      # checkout repo
      - uses: actions/checkout@v5

      # install node depuis .nvmrc
      - uses: actions/setup-node@v6 
        with:
          node-version-file: ".nvmrc"

      # installer les d√©pendances
      - run: npm ci 

      # lancer les tests unitaires
      - run: npm tests

      # lint le code
      - run: npm run lint
