name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  install:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_NAME: ${{ steps.generate-uuid.outputs.uuid }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate UUID
        id: generate-uuid
        run: |
          UUID=$(uuidgen)
          echo "IMAGE_NAME=${UUID}" >> $GITHUB_OUTPUT
          echo "::set-output IMAGE_NAME=uuid::${UUID}"
      - name: Build docker image
        run: docker build -t ttl.sh/${UUID}
      - name: Push docker image
        run: docker push ttl.sh/${UUID}:2h

  lint:
    runs-on: ubuntu-latest
    needs: install
    env:
      IMAGE_NAME: ${{ needs.install.outputs.IMAGE_NAME }}
    container:
      image: ttl.sh/${IMAGE_NAME}
    steps:
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: install
    env:
      IMAGE_NAME: ${{ needs.install.outputs.IMAGE_NAME }}
    container:
      image: ttl.sh/${IMAGE_NAME}
    steps:
      - run: npm test
